/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Activity Log": "活动日志",
    "and made by": "作者是",
    "Can you survive the apocalypse?": "你能在末日中幸存下来吗?",
    "Chop Wood": "砍木头",
    "Collect Water": "收集水",
    "Easy": "简单",
    "Gather Food": "采集食物",
    "Hard": "困难",
    "Medium": "中等",
    "No resources": "无资源",
    "open source": "开源的",
    "Try Again": "重新开始",
    "Upgrades": "升级",
    "Your society has collapsed.": "你的文明崩溃了。",
    "Your Party": "你的队伍",
    "Eat": "吃",
    "Drink": "喝",
    "Doctor": "医生",
    "IDLE": "空闲",
    "Health": "健康",
    "Hunger": "饥饿",
    "Hunter": "猎人",
    "Rest": "休息",
    "Mysterious Tracks": "神秘足迹",
    "Thirst": "口渴",
    "Lumberjack": "伐木工",
    "Farmer": "农民",
    "Farming": "耕作",
    "Big Family": "大家庭",
    "Hydrated": "水分充足",
    "Allows you to grow your own food": "允许你自己种植食物",
    "Big Game Hunter": "大型动物猎手",
    "Build the Hunting Lodge": "建造狩猎小屋",
    "Build the Medical Tent": "建造医疗帐篷",
    "Build the Tool Workshop": "建造工具作坊",
    "Build the Water Purification System": "建造净水系统",
    "Build the Well": "打井",
    "Could this help with wood production?": "这对木头生产有帮助吗?",
    "Could this provide water?": "这可以提供水吗?",
    "Crop Master": "作物大师",
    "Efficient": "非常高效。",
    "Energy": "能量",
    "Game started on easy difficulty with 1 people.": "游戏开始时只有1个人，难度很简单。",
    "Hunting Lodge": "狩猎小屋",
    "Increases resource gathering efficiency by 25% (more resources per action)": "提高25%的资源收集效率(每个行动增加更多资源)",
    "Jack of All Trades": "多面手",
    "Long-term Survivor": "长期的幸存者",
    "Marathon": "马拉松",
    "Master Farmer": "主人的农民",
    "Medical Tent": "医疗帐篷",
    "Mysterious Hole": "神秘的洞",
    "Mysterious Machinery": "神秘的机械",
    "Mysterious Plot of Land": "神秘的土地",
    "Mysterious Tower": "神秘的塔",
    "Plant your first crop": "种下第一种作物",
    "Slowly heals injured party members over time and reduces the chance of illness": "随着时间的推移慢慢治愈受伤的队友并减少生病的几率",
    "Survivor": "幸存者",
    "Tool Maker": "工具制造商",
    "Tool Workshop": "工具作坊",
    "Unlock Advanced Farming Techniques": "解锁先进的农业技术",
    "Unlock all upgrades": "解锁所有升级",
    "Unlocks a new \"Hunt\" action that has a chance to provide a large amount of food": "解锁一个新的“狩猎”行动，有机会提供大量的食物",
    "Water Purifier": "净水器",
    "Water Wizard": "水巫师",
    "Well Driller": "好钻孔机",
    "Well Fed": "营养充足",
    "Well Stocked": "储备充足",
    "What could grow here?": "这里能生长什么?",
    "What could we see from up there?": "从上面我们能看到什么?",
    "What creatures roam these lands?": "什么生物在这片土地上游荡?",
    "Unexpected Frost. There was an unexpected frost last night.": "意外的霜冻。昨晚有一场意想不到的霜冻。",
    "RESTING": "休息中",
    "\"The abyss gazes back...\"": "“深渊凝视着我…”",
    "Bountiful Harvest. Your crops look healthy": "丰富的收成。你的庄稼看起来很健康",
    "\"The water reflects faces that aren't there...\"": "“水反射出不存在的面孔……”",
    "Ancient Knowledge. You've found some interesting old documents.": "古老的知识。你找到了一些有趣的旧文件。",
    "Resources": "资源",
    "Time Survived": "生存时间",
    "No achievements unlocked": "没有解锁成就",
    "Game Over! Everyone has died.": "游戏结束! 全员凉凉。",
    "Game has been reset. All progress has been cleared.": "游戏已经重置。所有进度都已清除。",
    "\"Time flows backwards...\"": "“时光倒流……”",
    "Locust Swarm. A locust swarm passes through the area.": "蝗虫群。蝗群穿过这个地区。",
    "Advanced Farming Techniques": "先进的耕作技术",
    "Generates water over time": "随着时间的推移会产生水",
    "Increases crop yield by 50% and reduces growth time by 25%": "增加作物产量50%，减少生长时间25%",
    "Not enough water to plant this crop": "没有足够的水来种植这种作物",
    "Unlocked Farming": "解锁耕作",
    "Well": "水井",
    "Game started on medium difficulty with 3 people.": "游戏开始时只有3个人，中等难度。",
    "All crops are already watered": "所有作物都已浇水",
    "Game started on hard difficulty with 5 people.": "游戏一开始有5个人，难度很大。",
    "\"Ancient symbols appear in the dust...\"": "“古老的符号出现在尘土中……”",
    "Unlocked Well": "水井已解锁",
    "\"Forgotten gods demand tribute...\"": "\"被遗忘的神要求贡品…\"",
    "\"The ground hungers...\"": "\"大地在饥饿…\"",
    "\"The trees remember...\"": "\"树还记得……\"",
    "\"Time is running out...\"": "\"时间不多了……\"",
    "Reduces water consumption by 20% for all activities": "所有活动的用水量减少20%",
    "Unlocked Advanced Farming Techniques": "解锁先进农业技术",
    "Water Purification System": "净水系统",
    "Lumber Mill": "伐木场",
    "Hard Mission": "困难任务",
    "Easy Mission": "简单任务",
    "Rescue mission failed. The team returned empty-handed.": "救援任务失败。队员们空手而归。",
    "A easy rescue mission has been initiated. It will take 24 hours.": "一项简单的救援任务已经启动。需要24小时。",
    "A hard rescue mission has been initiated. It will take 72 hours.": "一项艰苦的救援任务已经启动。需要72小时。",
    "\"Echoes of unspoken words resonate...\"": "“未说出口的话语回响……”",
    "\"Memories of places never visited surface...\"": "“从未去过的地方的记忆浮现……”",
    "\"Reality bends and warps...\"": "“现实是弯曲和扭曲的……”",
    "\"Reality's seams become visible...\"": "“现实的缝隙变得清晰可见……”",
    "\"Reflections move independently...\"": "“倒影独立移动……”",
    "\"Shadows cast by nothing multiply...\"": "“虚无投射的阴影成倍增加……”",
    "\"Shadows dance without light...\"": "“没有光的影子会跳舞……”",
    "\"The boundaries of sanity blur...\"": "“理智的界限模糊了……”",
    "\"The earth trembles with anticipation...\"": "“大地因期待而颤抖……”",
    "\"The fabric of existence unravels...\"": "“存在的结构被解开了……”",
    "\"The shadows grow longer...\"": "“影子越来越长……”",
    "\"The silence screams...\"": "“寂静在尖叫……”",
    "\"The stars align in impossible patterns...\"": "“星星排成不可能的直线……”",
    "\"The void between thoughts expands...\"": "“思想之间的空隙扩大了……”",
    "\"The wind carries the scent of decay...\"": "“风带着腐烂的气味……”",
    "\"They're watching...\"": "\“他们在看…\”",
    "\"Time becomes a tangible substance...\"": "“时间变成了一种有形的物质……”",
    "\"Unseen eyes watch from every corner...\"": "“看不见的眼睛从每个角落注视着……”",
    "A rescue mission is available": "救援任务是可行的",
    "Allows you to spot and rescue potential survivors": "让你发现并营救潜在的幸存者",
    "Hunt the animal before it escapes": "在那动物逃跑前追捕它",
    "Rescue mission in progress:": "救援任务正在进行中:",
    "Time remaining:": "剩余时间:",
    "Unlocked Hunting Lodge": "狩猎小屋已解锁",
    "Unlocked Lumber Mill": "已解锁伐木场",
    "Unlocked Medical Tent": "已解锁医疗帐篷",
    "Unlocked Tool Workshop": "已解锁工具工坊",
    "Unlocked Watchtower": "已解锁瞭望塔",
    "Unlocked Water Purification System": "已解锁净水系统",
    "Watchtower": "瞭望塔",
    "Increases wood gathering efficiency by 50% and generates 1 wood per hour": "提高木材收集效率50%，每小时产生1块木材",
    "\"Forgotten rituals yearn to be performed...\"": "“被遗忘的仪式渴望被执行……”",
    "\"The moon weeps blood...\"": "“月亮流着血……”",
    "\"Whispers of madness grow louder...\"": "\“疯狂的低语越来越响……\”",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Society Failed": "文明末日",
    "Society Fail is": "文明末日（Society Fail）是",
    "Society Fail": "文明末日",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "@shpigford'": "@shpigford'",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Random Event: ": "随机事件: ",
    "Tool Breaking. One of your tools broke! (": "工具断裂。你的一个工具坏了!（",
    "BUSY [": "忙碌 [",
    "Rainstorm. A sudden rainstorm replenished your water supply! (": "下起倾盆大雨。一场突如其来的暴雨补充了你的水供应!（",
    "Achievement Unlocked: ": "成就解锁: ",
    "Lucky Find. You found a hidden cache of supplies! (": "幸运的发现。你找到了一个隐藏的补给仓库!(",
    "Wildlife Stampede. A stampede of animals trampled some of your food stores! (": "野生动物踩踏事件。一群动物踩踏了你的一些食物储备!（",
    "Quantum Fluctuation. A quantum fluctuation alters reality! ": "量子涨落。量子涨落会改变现实!",
    "Earthquake. An earthquake damages some structures! (": "地震。地震破坏了一些建筑物!（",
    "The Whispers: ": "低语者: ",
    "Reduces crop growth time by ": "减少作物生长时间 ",
    "Water all crops ": "给所有作物浇水 ",
    "Unexpected Visitor. A friendly traveler shared some food with your group! (": "意想不到的访客。一位友好的旅行者与你们分享了一些食物!（",
    "Tool Upgrade. You've found ways to improve your tools! ": "工具升级。你已经找到了改进工具的方法!",
    "Solar Flare. A solar flare disrupts sleep patterns! ": "太阳耀斑。太阳耀斑扰乱了睡眠模式! ",
    "Harsh Weather. A spell of harsh weather has drained everyone's energy! ": "恶劣的天气。一段时间的恶劣天气耗尽了每个人的精力!",
    "Tool Innovation. You've found a way to make your tools more efficient! ": "工具创新。你已经找到了一种使你的工具更有效的方法!",
    "Community Spirit. A wave of community spirit energizes everyone! ": "社区精神。一股社区精神的浪潮激励着每个人!",
    "Unexpected Frost. An unexpected frost has slowed the growth of your crops! ": "意想不到的霜冻。一场意想不到的霜冻减缓了你庄稼的生长!",
    "Mysterious Illness. A mysterious illness affects everyone in the group! ": "神秘的疾病。一种神秘的疾病影响着团队中的所有人!",
    "Water Contamination. Some of your water got contaminated! ": "水的污染。你的一些水被污染了!",
    "Windfall. A fallen tree provided extra wood! ": "意外之财。一棵倒下的树提供了额外的木材!",
    "Ancient Knowledge. You've uncovered ancient farming techniques! ": "古代的知识。你发现了古代的农业技术!",
    "Food Spoilage. Some of your food has spoiled! ": "食物变质。你的一些食物坏了!",
    "Locust Swarm. A locust swarm devours your crops! ": "蝗虫群。蝗虫群吞噬了你的庄稼!",
    "Shooting Star. A shooting star boosts everyone's spirits! ": "流星。流星让每个人都精神振奋!",
    "Bountiful Harvest. Your crops yielded an exceptional harvest! ": "丰收。你的庄稼大获丰收!",
    "Meteor Shower. A meteor shower brings rare minerals! ": "流星雨。流星雨带来了稀有的矿物!",
    "Natural Spring. You've discovered a natural spring! ": "天然泉水。你发现了一个天然的泉水!",
    "Time Anomaly. A strange time anomaly occurs! ": "时间异常。奇怪的时间异常发生了!",
    "Morale Boost. A surge of hope boosts everyone's morale! ": "提振士气。一股希望的浪潮鼓舞着每个人的士气!",
    "(1d, Low Risk, Cost: ": "(1天，低风险，成本:",
    "(2d, Moderate Risk, Cost: ": "(2天，中风险，成本:",
    "(3d, High Risk, Cost: ": "(3天，高风险，成本:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "!": "!",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Starting resources: (.+) food, (.+) water, (.+) wood.$/, '起始资源: $1 食物，$2 水，$3 木头。'],
    [/^Have (.+) of each resource at once$/, '同时拥有 $1 各种资源'],
    [/^Collected (.+) water from the well.$/, '从水井里面收集 $1 水'],
    [/^Have (.+) people in your party$/, '队伍中拥有 $1 人'],
    [/^Collect (.+) water from the well$/, '从水井收集 $1 水'],
    [/^Successfully hunt (.+) animals$/, '成功狩猎 $1 动物'],
    [/^Successfully hunted a turtle! Gained (.+) food.$/, '成功狩猎一只 乌龟！获得 $1 食物。'],
    [/^Successfully hunted a squirrel! Gained (.+) food.$/, '成功狩猎一只 松鼠！获得 $1 食物。'],
    [/^Successfully hunted a snail! Gained (.+) food.$/, '成功狩猎一只 蜗牛！获得 $1 食物。'],
    [/^Successfully hunted a rat! Gained (.+) food.$/, '成功狩猎一只 老鼠！获得 $1 食物。'],
    [/^Successfully hunted a rabbit! Gained (.+) food.$/, '成功狩猎一只 兔子！获得 $1 食物。'],
    [/^Successfully hunted a bird! Gained (.+) food.$/, '成功狩猎一只 鸟！获得 $1 食物。'],
    [/^(.+) ate food, reducing hunger by (.+) and recovering (.+) health and (.+) energy.$/, '$1 吃了食物，减少 $2 点饥饿，恢复 $3 点生命值和 $4 点能量'],
    [/^(.+) has died$/, '$1 挂了'],
    [/^Rescue mission failed. (.+) was injured during the attempt.$/, '救援任务失败。$1 在行动中受伤了。'],
    [/^Harvested wheat at row (.+), column (.+), yielding (.+) food.$/, '第 $1 行第 $2 列收获了小麦，收获 $3 食物。'],
    [/^Harvested carrot at row (.+), column (.+), yielding (.+) food.$/, '第 $1 行第 $2 列收获了胡萝卜，收获 $3 食物。'],
    [/^Harvested bean at row (.+), column (.+), yielding (.+) food.$/, '第 $1 行第 $2 列收获了豆子，收获 $3 食物。'],
    [/^Planted wheat at row (.+), column (.+).$/, '在第 $1 行第 $2 列种植小麦。'],
    [/^Planted bean at row (.+), column (.+).$/, '在第 $1 行第 $2 列种植豆子。'],
    [/^Planted carrot at row (.+), column (.+).$/, '在第 $1 行第 $2 列种植胡萝卜。'],
    [/^Harvested a fully grown tree for 10 wood.$/, '收获一棵成年树获得 $1 木头。'],
    [/^(.+) went to sleep.$/, '$1 去睡觉了。'],
    [/^(.+) chopped (.+) wood.$/, '$1 砍伐了 $2 木头。'],
    [/^(.+) collected (.+) water.$/, '$1 收集了 $2 水。'],
    [/^(.+) gathered (.+) food.$/, '$1 采集了 $2 食物。'],
    [/^(.+) drank water, reducing thirst by (.+) and recovering (.+) energy.$/, '$1 喝了水，口渴减少了 $2，恢复了 $3 能量。'],
    [/^Perform (.+) actions$/, '执行 $1 动作'],
    [/^Survive (.+) days$/, '生存 $1 天'],
    [/^Play for (.+) hours$/, '玩 $1 小时'],
    [/^Harvest (.+) crops$/, '收获 $1 作物'],
    [/^Accumulate (.+) food$/, '积累 $1 食物'],
    [/^Accumulate (.+) water$/, '积累 $1 水'],
    [/^Accumulate (.+) wood$/, '积累 $1 木头'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Alien Artifact. Liam found an alien artifact! \((.+) max energy, full health\)$/, '外星神器。$1 发现了一件外星神器!\($2 能量上限，满血\)'],
    [/^\((.+) health, (.+) energy for all\)$/, '\(所有人的生命值 $1，能量 $2\)'],
    [/^\((.+) hours pass instantly\)$/, '\(时光飞逝 $1\)'],
    [/^Cosmic Ray. (.+) was hit by a cosmic ray! \((.+) health\)$/, '宇宙射线。$1 被宇宙射线击中了!\(生命值 $2\)'],
    [/^\((.+) health for all\)$/, '\(所有人的生命值 $1\)'],
    [/^\((.+) to all resources\)$/, '\(所有资源 $1\)'],
    [/^\((.+) max energy for all\)$/, '\(所有人 $1 能量上限\)'],
    [/^Inspiring Dream. (.+) had an inspiring dream! \((.+) max energy\)$/, '鼓舞人心的梦想。$1 做了一个鼓舞人心的梦! \($2 能量上限\)'],
    [/^Wild Animal Attack. (.+) was attacked by a wild animal! \((.+) health\)$/, '野兽袭击。$1 被一只野兽袭击了! \($2 生命值\)'],
    [/^Illness. (.+) has fallen ill! \((.+) health\)$/, '疾病。$1 病了! \($2 生命值\)'],
    [/^\((.+) max crop capacity\)$/, '\($1 作物容量上限\)'],
    [/^\((.+) hour delay\)$/, '\(延迟 $1 小时\)'],
    [/^\((.+) energy for all\)$/, '\(所有人 $1 点能量\)'],
    [/^\((.+) stamina cost per action\)$/, '\(每动作消耗 $1 耐力\)'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h$/, '$1天 $2小时'],
    [/^([\d\.]+)day, ([\d\.]+)hours$/, '$1天 $2小时'],
    [/^([\d\.]+)days, ([\d\.]+)hours$/, '$1天 $2小时'],
    [/^\-([\d\.]+)days, ([\d\.]+)hours$/, '\-$1天 $2小时'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)h\]$/, '$1小时\]'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) days, ([\d\.,]+) hours$/, '$1 天，$2 小时'],
    [/^Day ([\d\.,]+) has begun.$/, '第 $1 天 开始了。'],
    [/^Day ([\d\.,]+), Hour ([\d\.,]+)$/, '$1 天，$2小时'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);